TI: arm: mach-k3: j7*: Fix warning due to typecasting
Few typecast was not done correctly, which leads to compile time
warnings.

/arch/arm/mach-k3/j784s4/j784s4_init.c: In function 'lpm_process':
/arch/arm/mach-k3/j784s4/j784s4_init.c:288:57: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  288 |         ret = ti_sci->ops.lpm_ops.lpm_save_addr(ti_sci, (u32)mem_addr_lpm.context_save_addr, mem_addr_lpm.size);
      |                                                         ^
/arch/arm/mach-k3/j784s4/j784s4_init.c: In function 'extract_lpm_region':
/arch/arm/mach-k3/j784s4/j784s4_init.c:316:42: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  316 |         mem_addr_lpm.context_save_addr = (u32 *)lpm_reg_addr;
      |                                          ^
/arch/arm/mach-k3/j784s4/j784s4_init.c: In function 'k3_mem_init':
/arch/arm/mach-k3/j784s4/j784s4_init.c:408:66: error: passing argument 2 of 'ti_secure_image_replay_cert' from incompatible pointer type [-Wincompatible-pointer-types]
  408 |                         ti_secure_image_replay_cert(&image_addr, &size_int);
      |                                                                  ^~~~~~~~~
      |                                                                  |
      |                                                                  u32 * {aka unsigned int *}
In file included from /arch/arm/mach-k3/j784s4/../common.h:11,
                 from /arch/arm/mach-k3/j784s4/j784s4_init.c:25:
/arch/arm/mach-k3/include/mach/security.h:13:58: note: expected 'size_t *' {aka 'long unsigned int *'} but argument is of type 'u32 *' {aka 'unsigned int *'}
   13 | void ti_secure_image_replay_cert(void **p_image, size_t *p_size);
      |                                                  ~~~~~~~~^~~~~~
/arch/arm/mach-k3/j784s4/j784s4_init.c:410:66: error: passing argument 2 of 'ti_secure_image_replay_cert' from incompatible pointer type [-Wincompatible-pointer-types]
  410 |                         ti_secure_image_replay_cert(&image_addr, &size_int);
      |                                                                  ^~~~~~~~~
      |                                                                  |
      |                                                                  u32 * {aka unsigned int *}
/arch/arm/mach-k3/include/mach/security.h:13:58: note: expected 'size_t *' {aka 'long unsigned int *'} but argument is of type 'u32 *' {aka 'unsigned int *'}
   13 | void ti_secure_image_replay_cert(void **p_image, size_t *p_size);
      |                                                  ~~~~~~~~^~~~~~
/arch/arm/mach-k3/j784s4/j784s4_init.c:415:60: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  415 |                         image_entry_noargs_t image_entry = (image_entry_noargs_t)loadaddr;
      |

Fix these warnings with proper typecast.

Reported-by: Siddharth Vadapalli <s-vadapalli@ti.com>
Signed-off-by: Udit Kumar <u-kumar1@ti.com>