configs: phycore_am62px_r5_ethboot_defconfig: Fix build error in ethboot config
The missing space character after the include directive causes
the phycore_am62px_r5_defconfig to be skipped during the ethboot build.

This fixes the following build error in ethboot config:
common/spl/spl.c:729:(.text.board_init_r+0x80): undefined reference to `spl_board_init'

Signed-off-by: John Ma <jma@phytec.com>
Signed-off-by: Wadim Egorov <w.egorov@phytec.de>